#!/bin/bash

set -e

scap sync-dir portals/prod/wikipedia.org/assets $*
scap sync-dir portals $*

# purgeList is called from from /srv/mediawiki-staging and not /srv/mediawiki
# to get an up-to-date version of the code and the config. That avoids any
# notice or error when there are config changes.
export MEDIAWIKI_STAGING_DIR=/srv/mediawiki-staging
cat /srv/mediawiki-staging/portals/urls-to-purge.txt | mwscript purgeList.php

